version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - db
    volumes:
      - ./db:/db  # Monte le dossier db pour accéder à init.py
    command: ["sh", "-c", "python db/init.py && python app.py"]

  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/app
    ports:
      - "8081:8081"

  db:
    container_name: database
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
